### ISSUE TITLE
Logo proposal for coin registry

### ISSUE THREAD

**Issue by memoryskull** [Blockmodo/coin_registry#11]
Hi! @coin_resgistry
I'm interested in collaborating with this initiative by delivering a series of logotype options that fits this project for the best!

If interested let me know so we can get started!

Cheers!

**Comment by electic** [comment]
Hi @memoryskull happy for you to help. Feel free to to take a look at the logos for BTC as an example. Drop me a note on Keybase, I am @electic on there.

**Comment by memoryskull** [comment]
HI @electic 
OK PERFECT WITHIN A LITTLE TIME I SHOW YOU THE PROPOSAL.

**Comment by memoryskull** [comment]
@electic Please give me all the information about your project
