### ISSUE TITLE
File Error Windows CON.registry.json

### ISSUE THREAD

**Issue by dArkjON** [Blockmodo/coin_registry#4]
Hi Guys,
very wired but the file name CON.registry is not possible to use, 
if i try to create a file with this name i get a error like "The specified device name is not allowed".

**Comment by electic** [comment]
I think you have to put .json at the end of the file name.

**Comment by dArkjON** [comment]
Afer pull the git to a local folder, my client immidently delete the file -> https://i.imgur.com/rumvALd.png

and when i try to restore it its not possible. I try to create a file with the Name Con.registry and also CON.registry.json but its Blocked from my System. 

Found this in a Microsoft Topic about it :
> Hi,
You can't make folders on the desktop that have "System Action" or "Device"  references such 
as con, nul and prn. Solution is to use another name or use 0 instead of o,O for C0n.

>Here are others :

>CON, PRN, AUX, CLOCK$, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, 
LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9 

https://answers.microsoft.com/en-us/windows/forum/windows_7-files/why-cant-i-create-a-folder-with-name/23c86662-4988-4c7d-9c2d-3e33d4413de3

**Comment by electic** [comment]
Oh weird, I am on a linux machine so maybe I didn't run into that. The best solution might be to just edit it in the browser. You can create a file via the GitHub git editor and just create it there.

**Comment by dArkjON** [comment]
Yeah i deselect the delete file so i was able to work without it.
but its not posible for a windows user to download this file...

windows issue by a text file :joy:
